-- Idempotent compatibility migration for columns used by Supabase insert/upsert payloads.
-- Note: the app's "subsidies" feature is implemented via public.reimbursements.

alter table if exists public.incomes
  add column if not exists user_id uuid,
  add column if not exists invoice_date date,
  add column if not exists payment_date date,
  add column if not exists customer_project text,
  add column if not exists category text,
  add column if not exists invoice_amount_original numeric(14,2) default 0,
  add column if not exists payment_received_original numeric(14,2) default 0,
  add column if not exists currency text,
  add column if not exists tax_mode text,
  add column if not exists exchange_rate numeric(12,6) default 1,
  add column if not exists exchange_rate_source text,
  add column if not exists exchange_rate_manual boolean default false,
  add column if not exists reporting_currency text,
  add column if not exists invoice_amount_reporting numeric(14,2) default 0,
  add column if not exists payment_received_reporting numeric(14,2) default 0,
  add column if not exists difference_original numeric(14,2) default 0,
  add column if not exists difference_reporting numeric(14,2) default 0,
  add column if not exists status text,
  add column if not exists description text;

alter table if exists public.expenses
  add column if not exists user_id uuid,
  add column if not exists expense_date date,
  add column if not exists payment_date date,
  add column if not exists category text,
  add column if not exists description text,
  add column if not exists original_amount numeric(14,2) default 0,
  add column if not exists currency text,
  add column if not exists tax_mode text,
  add column if not exists exchange_rate numeric(12,6) default 1,
  add column if not exists exchange_rate_source text,
  add column if not exists exchange_rate_manual boolean default false,
  add column if not exists reporting_currency text,
  add column if not exists amount_reporting numeric(14,2) default 0,
  add column if not exists deductible boolean default true,
  add column if not exists deductible_percentage numeric(5,2) default 100,
  add column if not exists deductible_amount_reporting numeric(14,2) default 0,
  add column if not exists receipt_available boolean default false,
  add column if not exists note text,
  add column if not exists is_depreciable boolean default false,
  add column if not exists acquisition_value numeric(14,2),
  add column if not exists acquisition_date date,
  add column if not exists useful_life_years integer,
  add column if not exists depreciation_method text,
  add column if not exists depreciation_warning text,
  add column if not exists reimbursable_to_client boolean default false,
  add column if not exists reimbursement_id uuid;

alter table if exists public.bank_fees
  add column if not exists user_id uuid,
  add column if not exists fee_date date,
  add column if not exists original_amount numeric(14,2) default 0,
  add column if not exists currency text,
  add column if not exists fee_type text,
  add column if not exists description text,
  add column if not exists exchange_rate numeric(12,6) default 1,
  add column if not exists exchange_rate_source text,
  add column if not exists exchange_rate_manual boolean default false,
  add column if not exists reporting_currency text,
  add column if not exists amount_reporting numeric(14,2) default 0,
  add column if not exists related_income_id uuid;

alter table if exists public.trips
  add column if not exists user_id uuid,
  add column if not exists title text,
  add column if not exists business_reason text,
  add column if not exists start_point text,
  add column if not exists start_at timestamptz,
  add column if not exists end_point text,
  add column if not exists end_at timestamptz,
  add column if not exists note text,
  add column if not exists total_km numeric(10,1) default 0,
  add column if not exists reporting_currency text,
  add column if not exists driving_deduction_reporting numeric(14,2) default 0,
  add column if not exists total_travel_expenses_reporting numeric(14,2) default 0,
  add column if not exists total_per_diem_reporting numeric(14,2) default 0,
  add column if not exists deductible_total_reporting numeric(14,2) default 0,
  add column if not exists mixed_trip_warning text,
  add column if not exists per_diem_breakdown jsonb default '[]'::jsonb,
  add column if not exists reimbursable_to_client boolean default false,
  add column if not exists reimbursement_id uuid;

alter table if exists public.trip_stops
  add column if not exists user_id uuid,
  add column if not exists trip_id uuid,
  add column if not exists sort_order integer,
  add column if not exists location text,
  add column if not exists country text,
  add column if not exists arrival_at timestamptz,
  add column if not exists departure_at timestamptz,
  add column if not exists purpose text,
  add column if not exists breakfast_provided boolean default false,
  add column if not exists lunch_provided boolean default false,
  add column if not exists dinner_provided boolean default false,
  add column if not exists note text;

alter table if exists public.trip_segments
  add column if not exists user_id uuid,
  add column if not exists trip_id uuid,
  add column if not exists sort_order integer,
  add column if not exists from_label text,
  add column if not exists to_label text,
  add column if not exists kilometers numeric(10,1) default 0,
  add column if not exists is_business boolean default true,
  add column if not exists deduction_reporting numeric(14,2) default 0,
  add column if not exists note text;

alter table if exists public.depreciations
  add column if not exists user_id uuid,
  add column if not exists linked_expense_id uuid,
  add column if not exists description text,
  add column if not exists original_amount numeric(14,2) default 0,
  add column if not exists currency text,
  add column if not exists exchange_rate numeric(12,6) default 1,
  add column if not exists exchange_rate_source text,
  add column if not exists exchange_rate_manual boolean default false,
  add column if not exists reporting_currency text,
  add column if not exists amount_reporting numeric(14,2) default 0,
  add column if not exists acquisition_date date,
  add column if not exists useful_life_years integer,
  add column if not exists yearly_amount_reporting numeric(14,2) default 0,
  add column if not exists deducted_until_year_reporting numeric(14,2) default 0,
  add column if not exists remaining_value_reporting numeric(14,2) default 0,
  add column if not exists remaining_years integer default 0,
  add column if not exists method text,
  add column if not exists note text;

alter table if exists public.reimbursements
  add column if not exists user_id uuid,
  add column if not exists reimbursement_date date,
  add column if not exists description text,
  add column if not exists original_amount numeric(14,2) default 0,
  add column if not exists currency text,
  add column if not exists tax_mode text,
  add column if not exists exchange_rate numeric(12,6) default 1,
  add column if not exists exchange_rate_source text,
  add column if not exists exchange_rate_manual boolean default false,
  add column if not exists reporting_currency text,
  add column if not exists amount_reporting numeric(14,2) default 0,
  add column if not exists context_type text,
  add column if not exists linked_record_id uuid,
  add column if not exists status text,
  add column if not exists note text,
  add column if not exists source_expense_id uuid,
  add column if not exists source_trip_id uuid;

alter table if exists public.settings
  add column if not exists user_id uuid,
  add column if not exists business_owner_name text,
  add column if not exists business_year integer,
  add column if not exists business_country text,
  add column if not exists reporting_currency text,
  add column if not exists theme_mode text default 'system',
  add column if not exists default_home_address text,
  add column if not exists default_currency text,
  add column if not exists default_manual_chf_eur_rate numeric(12,6) default 1,
  add column if not exists kleinunternehmer_mode boolean default true,
  add column if not exists default_tax_mode text,
  add column if not exists estimated_tax_rate numeric(5,2) default 0,
  add column if not exists steuerberater_view boolean default false;
